# Generated by Django 5.1.6 on 2025-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0005_alter_category_image_alter_city_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sticker',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
