# Generated by Django 5.1.6 on 2025-03-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0006_sticker_latitude_sticker_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='longitude',
        ),
    ]
