# Generated by Django 5.1.6 on 2025-03-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0007_remove_sticker_latitude_remove_sticker_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='navigation_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на навигацию (2GIS/Google Maps)'),
        ),
    ]
