# Generated by Django 5.1.6 on 2025-04-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0008_sticker_navigation_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='sticker_videos/'),
        ),
    ]
