# Generated by Django 5.2.1 on 2025-05-28 06:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0011_remove_chat_created_at_remove_like_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sticker',
            unique_together={('user', 'city', 'category', 'description')},
        ),
    ]
